apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-launch
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gke-launch
  template:
    metadata:
      labels:
        app: gke-launch
    spec:
      containers:
      - name: frontend
        image: gcr.io/conductive-fold-275020/frontend:latest
        ports:
        - containerPort: 8080
     - name:  backend
        image: gcr.io/conductive-fold-275020/backend:latest
        ports:
        - containerPort: 8081
