kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crud-pods
rules:
- apiGroups: [""]
  resources: ["pods", "deployments", "services"]
  verbs: ["list", "delete", "create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crud-pods
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: pods-list
  apiGroup: rbac.authorization.k8s.io