localhost:
  image: mongo:4.0.4
  ports: 
    - "27017:27017"

backend:
  build: .
  command: python -u app.py
  ports: 
    - "27017:27017
  volumes: 
    - ./todo
  links: 
    - localhost
    